id = "gruvbox-material"
name = "Gruvbox Material"
version = "1.0.0"
schema_version = 1
authors = ["tokiory <tokiory.work@gmail.com>"]
repository = "https://github.com/tokiory/zed-gruvbox-material"
description = "Gruvbox Material theme for Zed editor"
